server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: employees
          uri: http://localhost:8081/
          predicates:
            - Path=/api/employees
          filters:
            - AddRequestHeader=X-Request-Message, HelloTraining
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/api/employees/fake

management:
  tracing:
    sampling:
      probability: 1.0

